include $(LITEOSTOPDIR)/config.mk

MODULE_NAME := mbedtls
LOCAL_SRCS := $(wildcard $(LITEOSTOPDIR)/../../third_party/mbedtls/library/*.c)
LOCAL_INCLUDE := -I$(LITEOSTOPDIR)/../../third_party/mbedtls/include/
LOCAL_FLAGS := $(LOCAL_INCLUDE)

include $(MODULE)
